In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
train_df = pd.read_csv(Path('Resources/Generator/2019loans.csv'))
train_df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,7000.0,0.1894,256.38,MORTGAGE,75000.0,Not Verified,n,28.62,0.0,2.0,...,87.5,0.0,0.0,352260.0,62666.0,35000.0,10000.0,N,N,low_risk
1,40000.0,0.1614,975.71,MORTGAGE,102000.0,Source Verified,n,11.72,2.0,0.0,...,0.0,0.0,0.0,294664.0,109911.0,9000.0,71044.0,N,N,low_risk
2,11000.0,0.2055,294.81,RENT,45000.0,Verified,n,37.25,1.0,3.0,...,7.7,0.0,0.0,92228.0,36007.0,33000.0,46328.0,N,N,low_risk
3,4000.0,0.1612,140.87,MORTGAGE,38000.0,Not Verified,n,42.89,1.0,0.0,...,100.0,0.0,0.0,284273.0,52236.0,13500.0,52017.0,N,N,low_risk
4,14000.0,0.1797,505.93,MORTGAGE,43000.0,Source Verified,n,22.16,1.0,0.0,...,25.0,0.0,0.0,120280.0,88147.0,33300.0,78680.0,N,N,low_risk

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2 = train_df.copy()
df2['home_ownership'] = le.fit_transform(df2['home_ownership'])
df2['verification_status'] = le.fit_transform(df2['verification_status'])
df2['pymnt_plan'] = le.fit_transform(df2['pymnt_plan'])
df2['hardship_flag'] = le.fit_transform(df2['hardship_flag'])
df2['debt_settlement_flag'] = le.fit_transform(df2['debt_settlement_flag'])
df2['target'] = le.fit_transform(df2['target'])
df2.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,7000.0,0.1894,256.38,1,75000.0,0,0,28.62,0.0,2.0,...,87.5,0.0,0.0,352260.0,62666.0,35000.0,10000.0,0,0,1
1,40000.0,0.1614,975.71,1,102000.0,1,0,11.72,2.0,0.0,...,0.0,0.0,0.0,294664.0,109911.0,9000.0,71044.0,0,0,1
2,11000.0,0.2055,294.81,3,45000.0,2,0,37.25,1.0,3.0,...,7.7,0.0,0.0,92228.0,36007.0,33000.0,46328.0,0,0,1
3,4000.0,0.1612,140.87,1,38000.0,0,0,42.89,1.0,0.0,...,100.0,0.0,0.0,284273.0,52236.0,13500.0,52017.0,0,0,1
4,14000.0,0.1797,505.93,1,43000.0,1,0,22.16,1.0,0.0,...,25.0,0.0,0.0,120280.0,88147.0,33300.0,78680.0,0,0,1

In [4]:
test_df = pd.read_csv(Path('Resources/Generator/2020Q1loans.csv'))
test_df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,40000.0,0.1033,856.40,RENT,128700.0,Source Verified,n,12.47,0.0,1.0,...,57.1,0.0,0.0,63915.0,49510.0,49400.0,14515.0,Y,N,low_risk
1,24450.0,0.1430,572.72,MORTGAGE,44574.0,Not Verified,n,15.05,0.0,1.0,...,0.0,0.0,0.0,136425.0,19439.0,15500.0,18925.0,N,N,low_risk
2,13500.0,0.1430,316.23,OWN,60000.0,Not Verified,n,28.72,0.0,0.0,...,0.0,0.0,0.0,82124.0,65000.0,5400.0,61724.0,Y,N,low_risk
3,10625.0,0.1774,268.31,RENT,60000.0,Verified,n,15.70,0.0,4.0,...,20.0,0.0,0.0,54855.0,50335.0,23200.0,26255.0,N,N,low_risk
4,6375.0,0.1862,232.46,RENT,60000.0,Source Verified,n,35.50,0.0,0.0,...,75.0,0.0,0.0,90445.0,56541.0,15300.0,72345.0,N,N,low_risk

In [5]:
df3= test_df.copy()
df3 = le.fit_transform(df3)

ValueError: y should be a 1d array, got an array of shape (4702, 84) instead.

In [ ]:
le = LabelEncoder()
df2 = test_df.copy()
df2['home_ownership'] = le.fit_transform(df2['home_ownership'])
df2['verification_status'] = le.fit_transform(df2['verification_status'])
df2['pymnt_plan'] = le.fit_transform(df2['pymnt_plan'])
df2['hardship_flag'] = le.fit_transform(df2['hardship_flag'])
df2['debt_settlement_flag'] = le.fit_transform(df2['debt_settlement_flag'])
df2['target'] = le.fit_transform(df2['target'])
df2['initial_list_status'] = le.fit_transform(df2['initial_list_status'])
df2.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,40000.0,0.1033,856.40,3,128700.0,1,0,12.47,0.0,1.0,...,57.1,0.0,0.0,63915.0,49510.0,49400.0,14515.0,1,0,1
1,24450.0,0.1430,572.72,1,44574.0,0,0,15.05,0.0,1.0,...,0.0,0.0,0.0,136425.0,19439.0,15500.0,18925.0,0,0,1
2,13500.0,0.1430,316.23,2,60000.0,0,0,28.72,0.0,0.0,...,0.0,0.0,0.0,82124.0,65000.0,5400.0,61724.0,1,0,1
3,10625.0,0.1774,268.31,3,60000.0,2,0,15.70,0.0,4.0,...,20.0,0.0,0.0,54855.0,50335.0,23200.0,26255.0,0,0,1
4,6375.0,0.1862,232.46,3,60000.0,1,0,35.50,0.0,0.0,...,75.0,0.0,0.0,90445.0,56541.0,15300.0,72345.0,0,0,1

In [ ]:
y = df2["target"]
target_names = ["negative", "positive"]

In [ ]:
data = df2.drop("target", axis=1)
feature_names = data.columns
data.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,40000.0,0.1033,856.40,3,128700.0,1,0,12.47,0.0,1.0,...,84.2,57.1,0.0,0.0,63915.0,49510.0,49400.0,14515.0,1,0
1,24450.0,0.1430,572.72,1,44574.0,0,0,15.05,0.0,1.0,...,100.0,0.0,0.0,0.0,136425.0,19439.0,15500.0,18925.0,0,0
2,13500.0,0.1430,316.23,2,60000.0,0,0,28.72,0.0,0.0,...,100.0,0.0,0.0,0.0,82124.0,65000.0,5400.0,61724.0,1,0
3,10625.0,0.1774,268.31,3,60000.0,2,0,15.70,0.0,4.0,...,91.4,20.0,0.0,0.0,54855.0,50335.0,23200.0,26255.0,0,0
4,6375.0,0.1862,232.46,3,60000.0,1,0,35.50,0.0,0.0,...,100.0,75.0,0.0,0.0,90445.0,56541.0,15300.0,72345.0,0,0

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 84 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   4702 non-null   float64
 1   int_rate                    4702 non-null   float64
 2   installment                 4702 non-null   float64
 3   home_ownership              4702 non-null   int64
 4   annual_inc                  4702 non-null   float64
 5   verification_status         4702 non-null   int64
 6   pymnt_plan                  4702 non-null   int64
 7   dti                         4702 non-null   float64
 8   delinq_2yrs                 4702 non-null   float64
 9   inq_last_6mths              4702 non-null   float64
 10  open_acc                    4702 non-null   float64
 11  pub_rec                     4702 non-null   float64
 12  revol_bal                   4702 non-null   float64
 13  total_acc                   4702 non-null   float64
 14  initial_list_status         4702 non-null   int64
 15  out_prncp                   4702 non-null   float64
 16  out_prncp_inv               4702 non-null   float64
 17  total_pymnt                 4702 non-null   float64
 18  total_pymnt_inv             4702 non-null   float64
 19  total_rec_prncp             4702 non-null   float64
 20  total_rec_int               4702 non-null   float64
 21  total_rec_late_fee          4702 non-null   float64
 22  recoveries                  4702 non-null   float64
 23  collection_recovery_fee     4702 non-null   float64
 24  last_pymnt_amnt             4702 non-null   float64
 25  collections_12_mths_ex_med  4702 non-null   float64
 26  policy_code                 4702 non-null   float64
 27  application_type            4702 non-null   object
 28  acc_now_delinq              4702 non-null   float64
 29  tot_coll_amt                4702 non-null   float64
 30  tot_cur_bal                 4702 non-null   float64
 31  open_acc_6m                 4702 non-null   float64
 32  open_act_il                 4702 non-null   float64
 33  open_il_12m                 4702 non-null   float64
 34  open_il_24m                 4702 non-null   float64
 35  mths_since_rcnt_il          4702 non-null   float64
 36  total_bal_il                4702 non-null   float64
 37  il_util                     4702 non-null   float64
 38  open_rv_12m                 4702 non-null   float64
 39  open_rv_24m                 4702 non-null   float64
 40  max_bal_bc                  4702 non-null   float64
 41  all_util                    4702 non-null   float64
 42  total_rev_hi_lim            4702 non-null   float64
 43  inq_fi                      4702 non-null   float64
 44  total_cu_tl                 4702 non-null   float64
 45  inq_last_12m                4702 non-null   float64
 46  acc_open_past_24mths        4702 non-null   float64
 47  avg_cur_bal                 4702 non-null   float64
 48  bc_open_to_buy              4702 non-null   float64
 49  bc_util                     4702 non-null   float64
 50  chargeoff_within_12_mths    4702 non-null   float64
 51  delinq_amnt                 4702 non-null   float64
 52  mo_sin_old_il_acct          4702 non-null   float64
 53  mo_sin_old_rev_tl_op        4702 non-null   float64
 54  mo_sin_rcnt_rev_tl_op       4702 non-null   float64
 55  mo_sin_rcnt_tl              4702 non-null   float64
 56  mort_acc                    4702 non-null   float64
 57  mths_since_recent_bc        4702 non-null   float64
 58  mths_since_recent_inq       4702 non-null   float64
 59  num_accts_ever_120_pd       4702 non-null   float64
 60  num_actv_bc_tl              4702 non-null   float64
 61  num_actv_rev_tl             4702 non-null   float64
 62  num_bc_sats                 4702 non-null   float64
 63  num_bc_tl                   4702 non-null   float64
 64  num_il_tl                   4702 non-null   float64
 65  num_op_rev_tl               4702 non-null   float64
 66  num_rev_accts               4702 non-null   float64
 67  num_rev_tl_bal_gt_0         4702 non-null   float64
 68  num_sats                    4702 non-null   float64
 69  num_tl_120dpd_2m            4702 non-null   float64
 70  num_tl_30dpd                4702 non-null   float64
 71  num_tl_90g_dpd_24m          4702 non-null   float64
 72  num_tl_op_past_12m          4702 non-null   float64
 73  pct_tl_nvr_dlq              4702 non-null   float64
 74  percent_bc_gt_75            4702 non-null   float64
 75  pub_rec_bankruptcies        4702 non-null   float64
 76  tax_liens                   4702 non-null   float64
 77  tot_hi_cred_lim             4702 non-null   float64
 78  total_bal_ex_mort           4702 non-null   float64
 79  total_bc_limit              4702 non-null   float64
 80  total_il_high_credit_limit  4702 non-null   float64
 81  hardship_flag               4702 non-null   int64
 82  debt_settlement_flag        4702 non-null   int64
 83  target                      4702 non-null   int64
dtypes: float64(76), int64(7), object(1)
memory usage: 3.0+ MB

In [ ]:
# Convert categorical data to numeric and separate target feature for training data
# Convert categorical data to numeric and separate target feature for testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, y, random_state=1, stratify=y)

In [ ]:
# add missing dummy variables to testing set

In [ ]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)
classifier
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: 'Individual'

In [ ]:
# Train a Random Forest Classifier model and print the model score

In [ ]:
# Scale the data
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [ ]:
# Train the Logistic Regression model on the scaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score